apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-backend
  labels:
    app: backend
spec:
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
        version: ${VERSION}
    spec:
      containers:
        - name: capstone-fe
          image: divyavan/capstone-backend:${VERSION}
          ports:
            - containerPort: 5000
