apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-backend
  labels:
    app: backend
spec:
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
        version: v2
    spec:
      containers:
        - name: capstone-be
          image: divyavan/capstone-backend:v2
          env:
            - name: REDIS_FROM_URL
              value:  redis://capstone-redis:6379
          ports:
            - containerPort: 5000
