version: "3.9"
services:
  capstone-frontend:
    build: 
      context: frontend
      dockerfile: Dockerfile_v2
    image: capstone-frontend:latest
    ports:
      - 5000:5000
    environment:
      COUNTER_SERVICE_URL: http://capstone-backend:5000
  capstone-backend:
    build:
      context: backend
      dockerfile: Dockerfile_v2
    image: capstone-backend:latest
    environment:
      REDIS_FROM_URL: redis://capstone-redis:6379
  capstone-redis:
    image: redis:7.0-bullseye
  jaegertracing:
    image: jaegertracing/all-in-one
    ports:
      - 16686:16686
      - 14268:14268
