apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-jaeger
  labels:
    app: jaeger
spec:
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      labels:
        app: jaeger
    spec:
      containers:
        - name: jaegertracing
          image: jaegertracing/all-in-one
          ports:
            - containerPort: 16686
            - containerPort: 14268
