apiVersion: v1
kind: Service
metadata:
  name: jaegertracing
spec:
  type: NodePort
  selector:
    app: jaeger
  ports:
    - protocol: TCP
      name: jaeger-ui
      port: 16686
      targetPort: 16686
    - protocol: TCP
      name: jaeger-endpoint
      port: 14268
      targetPort: 14268