apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-redis
  labels:
    app: redis
spec:
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: capstone-redis
          image: redis:7.0-bullseye
          ports:
            - containerPort: 6379
